### PR TITLE
FOR REVIEW ONLY - js-algorand-sdk v1.13.0

### PR DESCRIPTION
**Pull request by algobarb**
# 1.13.0

## Added:

- Create dryrun (#478)
- Support ABI reference types and other improvements (#482)
- Improve HTTP error messages (#485)
- Enabling a custom client for Algod and Indexer (#477)
- Export sdk subclasses to typedoc (#479)
- ABI Support for JS library (#454)
- ABI interaction support (#466)
- Wait for confirmation function (#469)
- Add freezeAccount encoding in display method (#460)
- Regenerate code from specification file (#456)

## Changed:

- Document Indexer methods (#491)
- Document Algodv2 methods (#486)
- Update chromedriver (#492)

## Fixed:

- Fix wait for confirmation function (#480)
- Fix type for foreignAssets (#472)

### CODE REVIEW

**Comment by jasonpaulos** [comment]
Do we want to squash the changelogs for 1.13.0-beta.1 and -beta.2 into 1.13.0?

I'm not sure what the best practice is for this.

**Comment by algobarb** [comment]
> Do we want to squash the changelogs for 1.13.0-beta.1 and -beta.2 into 1.13.0?
> 
> I'm not sure what the best practice is for this.

I took the description from #493, but I think you're right. It makes sense to squash the beta notes under 1.13.0 as well.

**Comment by algobarb** [comment]
I added 1.13.0-beta.1 and -beta.2 notes into 1.13.0 in the changelog, while leaving 1.13.0-beta.1 and -beta.2 changelogs alone for binary reference. I think it might be useful to keep the beta release changelog notes too, but I'm not sure. 

What do you prefer to see? @onetechnical @jasonpaulos

**Review by jasonpaulos — APPROVED** [review]
This looks good to me

**Review by onetechnical — APPROVED** [review]

**Review by barnjamin — APPROVED** [review]

**Pull request merged**
