### PR TITLE
Added a new example.

### PR DESCRIPTION
**Pull request by Bhaney44**
Following up on [PR #646 Choice Connect](https://github.com/algorand/js-algorand-sdk/pull/646), which was rejected for lack of showcasing the Javascript-SDK enough relative to Pera Wallet. I created a new example, which does more to showcase the capabilities of the JavaScript-SDK by creating a game where a user wins a prize. This contribution is made in response to [Issue #150](https://github.com/algorandfoundation/grow-algorand/issues/150) on the Algorand Foundation GitHub.

### CODE REVIEW

**Comment by Bhaney44** [comment]
Hi, @jasonpaulos I hope all is well. I wanted to request a review on this please.

With thanks,

Brian

**Comment by Bhaney44** [comment]
Hi @jasonpaulos I hope all is well. Just wanted to follow up on this.

Thanks,

Brian

**Comment by barnjamin** [comment]
Hi @Bhaney44, thanks for the effort here but this is not something that really belongs in the SDK itself for a number of reasons including; new dependencies, support effort required, and branded or licensed content. 

Perhaps consider a blog post on medium?

**Comment by Bhaney44** [comment]
> Issue #150

Hi Ben, Thanks for the reply. I will file an Issue first in the future before making a PR.  

Regarding the [license](https://github.com/algorandfoundation/grow-algorand/issues/150) however, Issue 150 expressly requires contributions have an attributed license.

`All project codes should be published on GitHub, with MIT license or Apache V2 license.`

**Comment by Bhaney44** [comment]
> Hi @Bhaney44, thanks for the effort here but this is not something that really belongs in the SDK itself for a number of reasons including; new dependencies, support effort required, and branded or licensed content.
> 
> Perhaps consider a blog post on medium?
> 
> In the future a good way to go about this would be to file an Issue first where the idea and scope of work can be discussed before starting on anything.

I wanted to follow up on the @barnjamin. I went to open an Issue for a new contribution, but the only issues available to be opened are bug reports and feature requests. Given Algorand Foundation [Issue 150](https://github.com/algorandfoundation/grow-algorand/issues/150), how would you like me to proceed with making contributions? Thanks.

**Pull request closed without merging**
