### PR TITLE
Added support for non participation (nonpart) flag in keyreg transaction

### PR DESCRIPTION
**Pull request by code-dev-ai**

### CODE REVIEW

**Comment by jasonpaulos** [comment]
Hi @code-dev-ai, thanks for creating this. I'd be happy to merge it once you sign the CLA.

**Comment by code-dev-ai** [comment]
> Hi @code-dev-ai, thanks for creating this. I'd be happy to merge it once you sign the CLA.

@jasonpaulos I have signed the CLA, but it is not showing here as signed. Can you please check? Please let me know if there is anything more that I need to do.

**Comment by jasonpaulos** [comment]
It looks like @pancham88 was the author of the commit, so they'll need to sign the CLA. Once that happens, I can accept.

Also, I added a unit test and some additional changes.

**Comment by code-dev-ai** [comment]
Thanks for adding unit tests. 
pancham88 user has signed the CLA.

**Review by jasonpaulos — APPROVED** [review]

**Pull request merged**
