### PR TITLE
Enhancement: Upgrade typedoc and plugins

### PR DESCRIPTION
**Pull request by fionnachan**
maintenance & a better looking (and UX) doc site

Deployed version:
https://upgrade-typedoc-and-plugins--js-algosdk.netlify.app/

### CODE REVIEW

**Comment by fionnachan** [comment]
no permission to add labels ^_^"

**Review by Eric-Warehime — APPROVED** [review]
Looks good to me! We should update the gh-pages branch to get any generated doc changes deployed.

**Comment by fionnachan** [comment]
I am not sure how the `gh-pages` branch is updated. I assume you have a CI/CD workflow set up for automatic updates?

**Comment by Eric-Warehime** [comment]
It looks like CircleCI got stuck in "waiting" even though it's not running a workflow. Going to try closing and re-opening to see if that will trigger a new test run.

**Comment by fionnachan** [comment]
Thanks, the browser tests failed because of an issue related to `ts-node` and `typescript` perhaps due to the update of other dependencies.
Let's see if updating these two works.

https://stackoverflow.com/questions/72586253/typescript-debug-failure-false-expression-non-string-value-passed-to-ts-reso

**Pull request merged**
