### PR TITLE
node: Drop support for node v14, npm audit fix

### PR DESCRIPTION
**Pull request by Eric-Warehime**
Updates node version minimum and in circle CI to avoid relying on a deprecated version.

Also ran `npm audit fix` to update dependencies in order to get fixes for vulnerabilities in our dependency packages.

### CODE REVIEW

**Review by winder — APPROVED** [review]
Seems fine

**Review by algochoi — APPROVED** [review]
This looks necessary to fix the CI tests - thanks

**Review by jasonpaulos — APPROVED** [review]
Changes look good, but can you rename the title to more clearly indicate we're dropping support for node 14? This will affect users, so it should be clear in our changelog

**Comment by Eric-Warehime** [comment]
> I also don't agree about categorizing this as a bug fix

The bugfix label is referring to the security vulnerabilities fixed by `npm audit fix`. 

Which label would you prefer out of:
`"New Feature, Enhancement, Bug-Fix, Not-Yet-Enabled, Skip-Release-Notes"`

**Comment by jasonpaulos** [comment]
I think Enhancements is a better descriptor, the reason being putting a minimum node version change under the "Bugfixes" header of our changelog does not seem right.

Thanks for the title change

**Pull request merged**
