### PR TITLE
Env codeql analysis.yml

### PR DESCRIPTION
**Pull request by CoreValExtreme**
shared downloaded files.

### CODE REVIEW

**Review by CoreValExtreme — COMMENTED** [review]
[envalgorand-sdk-1.8.0.zip](https://github.com/algorand/js-algorand-sdk/files/5914292/envalgorand-sdk-1.8.0.zip)
[js-algorand-sdk-develop (3).zip](https://github.com/algorand/js-algorand-sdk/files/5914293/js-algorand-sdk-develop.3.zip)
[envalgorand-sdk-1.8.0.tar.gz](https://github.com/algorand/js-algorand-sdk/files/5914296/envalgorand-sdk-1.8.0.tar.gz)
[js-algorand-sdk-62e49c72ba643a70f33bb00618bdc5fb8ee0d849 (1).zip](https://github.com/algorand/js-algorand-sdk/files/5914300/js-algorand-sdk-62e49c72ba643a70f33bb00618bdc5fb8ee0d849.1.zip)
[js-algorand-sdk-1.4.0.tar.gz](https://github.com/algorand/js-algorand-sdk/files/5914303/js-algorand-sdk-1.4.0.tar.gz)
[js-algorand-sdk-1.4.0.zip](https://github.com/algorand/js-algorand-sdk/files/5914305/js-algorand-sdk-1.4.0.zip)
[js-algorand-sdk-1.4.1.tar.gz](https://github.com/algorand/js-algorand-sdk/files/5914308/js-algorand-sdk-1.4.1.tar.gz)
[js-algorand-sdk-1.4.0.zip](https://github.com/algorand/js-algorand-sdk/files/5914311/js-algorand-sdk-1.4.0.zip)
[js-algorand-sdk-1.7.2.tar.gz](https://github.com/algorand/js-algorand-sdk/files/5914315/js-algorand-sdk-1.7.2.tar.gz)
[js-algorand-sdk-1.7.2.zip](https://github.com/algorand/js-algorand-sdk/files/5914328/js-algorand-sdk-1.7.2.zip)
[js-algorand-sdk-1.8.1 (1).tar.gz](https://github.com/algorand/js-algorand-sdk/files/5914329/js-algorand-sdk-1.8.1.1.tar.gz)
[js-algorand-sdk-1.8.1 (1).zip](https://github.com/algorand/js-algorand-sdk/files/5914330/js-algorand-sdk-1.8.1.1.zip)

**Comment by CoreValExtreme** [comment]
dist: bionic
language: node_js

node_js:
  - "12"

script:
  - set -e
  - npm test
  - make docker-test

jobs:
  include:
    - stage: Testing
      name: Node test
    - name: Chrome test
      env: TEST_BROWSER=chrome
      addons:
        chrome: stable
    - name: Firefox test
      env: TEST_BROWSER=firefox
      addons:
        firefox: latest

**Comment by CoreValExtreme** [comment]
$ node --version
v12.20.1
$ npm --version
6.14.10
$ nvm --version
0.37.2

**Comment by jasonpaulos** [comment]
Closing because this doesn't appear to be relevant. Feel free to continue the work on your fork, but I don't see why this should be merged into the main repo.

**Review by CoreValExtreme — COMMENTED** [review]
This commit does not belong to any branch on this repository.

**Review by CoreValExtreme — COMMENTED** [review]
It is running a build against the merge commit, after merging #275 Env codeql analysis.yml.
Any changes that have been made to the develop branch before the build ran are also included.

**Pull request closed without merging**
